package bot.tg.state;

public enum UserState {
    IDLE,
    SETTINGS,
    ADJUSTING_TIMEZONE,
    AWAITING_LOCATION,
    TIMEZONE_MANUAL_CHOICE,
    GOOGLE_CONNECT,
    GOOGLE_DISCONNECT,
    SWITCH_GOOD_MORNING,
    AWAITING_TASK_SELECTION,
    AWAITING_TASK_TITLE,
    AWAITING_TASK_DESCRIPTION,
    AWAITING_REMINDER_SELECTION,
    AWAITING_REMINDER_DATE,
    AWAITING_REMINDER_TIME,
    AWAITING_REMINDER_TEXT
}
